### ISSUE TITLE
Generate Go Tests in Sublime Text 3 giving error as "error: [Errno 2] No such file or directory: 'gotests'."

### ISSUE THREAD

**Issue by sudheernayudu** [cweill/gotests#21]
This might be a trivial configuration issue, but i was unable to figure out. I configured user gotests sublime settings with right GOPATH. All other golang plugins are working fine. My OS is OS X El Captain.
GoTests is perfectly working from command line. Please help in resolving this..

**Comment by sudheernayudu** [comment]
This might be a trivial configuration issue, but i was unable to figure out. I configure user gotests sublime settings with right GOPATH. All other golang plugins are working fine. By the way i'm using OS X El Captain.

**Comment by cweill** [comment]
Hey any luck since then? Just to double check, you ran `go get github.com/cweill/gotests/...` and then added set your __absolute__ GOPATH in the `GoTests.sublime-settings` file?

Try launching Sublime from the terminal and see if that helps. If it does, it means your shell environment variables may be loaded when you launch Sublime another way (say by opening it from the application dock). 

Worst case scenario: hard code the `/absolute/path/to/gotests` in for the `gotests_cmd` key. See https://github.com/cweill/GoTests-Sublime/blob/master/GoTests.sublime-settings.

**Comment by sudheernayudu** [comment]
Thanks a lot. It worked perfect after providing absolute path of gotests in gotests_cmd.

**Comment by cweill** [comment]
No problem. Glad I could help!
