### ISSUE TITLE
Allow to optionally use testify

### ISSUE THREAD

**Issue by rigelrozanski** [cweill/gotests#47]
Open to coding this one if there is support to merge... 
I'm a huge fan of the testing package testify for printing errors during testing: 
github.com/stretchr/testify/assert

It would be cool to have a flag which allowed for use of this package instead of the standard error print which is currently being used... here is an example of how this change would look: 

old:
```golang
	if err := tx.ValidateBasic(); (err != nil) != tt.wantErr {
		t.Errorf("TxModComm.ValidateBasic() error = %v, wantErr %v", err, tt.wantErr)
	}
```
with testify: 
```golang
	assert.Equal(t, tt.wantErr, tx.ValidateBasic() != nil, tt.name)
```

Obviously, this is for a simple error function, but assert does provide a variety of different comparisons as well. Let me know any thoughts! I'll probably end up making a branch which uses assert anyways, but I'll make it optional with a flag if there is an opportunity to merge this back in.

**Comment by cweill** [comment]
Hi @rigelrozanski - I like the idea, but I am a little conflicted since I would prefer to minimize third-party dependencies. However, if you can add `testify` support while maintaining backwards compatibility, and keep all `testify` code modularized and independent from the rest of the source, I would be open to merging the change.

**Comment by rigelrozanski** [comment]
Okay awesome... yeah I understand your desire to minimize 3rd party packages. I'll see how modular I am able to make this once I get around to this

**Comment by cweill** [comment]
I've been playing with the idea of allowing users to define their own template (see #5). I haven't had much time to look into it since I haven't been doing as much Go development lately, but I would be happy to provide guidance for a clean design. 

Since templates can be parsed from files, we could define a template "interface". Then the user can just point to the directory contain the template via a flag, include the files, and allow gotests to use them without touching any code.

**Comment by cweill** [comment]
If anyone wants to create some testify templates for the `-templates_dir` flag, I can review them and add them to this repository.

**Comment by shihanng** [comment]
@cweill I would very much like to send in the templates for testify. I've modified the function template based on https://github.com/cweill/gotests/tree/17e4e80b8a3898088c7a316fc614f2443bfa3884/internal/render/templates

However I could not figure out where should I put the custom templates. Could you let me know where should the custom templates be placed? Thank you very much.

**Comment by cweill** [comment]
@shihanng Feel free to send a PR and add a new directory called `templates/` in the root dir next to `gotests.go`. Then you can add a flag to the binary called `--template` and have one be `"testify"`.
